import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Script from "next/script";
import { getAllSlugs, getAllRecipes } from "../lib/recipes";

interface Props {
  recipes: {
    slug: string;
    title: string;
  }[];
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const recipes = getAllRecipes().map(({ slug, title }) => {
    return {
      slug,
      title,
    };
  });

  return {
    props: {
      recipes,
    },
  };
};

const Home: NextPage<Props> = ({ recipes }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script
          src="https://identity.netlify.com/v1/netlify-identity-widget.js"
          async
          defer
        ></Script>
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Welcome to it <a href="https://nextjs.org">Hello!</a>
        </h1>
        <ul>
          {recipes.map(({ slug, title }) => (
            <li key={slug}>
              <Link href={`/${slug}`}>{title}</Link>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
