import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://identity.netlify.com/v1/netlify-identity-widget.js"
          async
          defer
        ></script>
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Welcome to <a href="https://nextjs.org">Hello!</a>
        </h1>
      </main>
    </>
  );
};

export default Home;
